### ISSUE TITLE
Format the already present quotes

### ISSUE THREAD

**Issue by ab-anand** [ab-anand/fav-quote#18]
Some of the contributors have added their quotes. But it is not in proper format as specified in [CONTRIBUTING.md](https://github.com/ab-anand/fav-quote/blob/master/CONTRIBUTING.md)

You can check out the Contributing Guidelines and format them properly.

**Comment by saideepesh000** [comment]
can i work on this

**Comment by ab-anand** [comment]
@saideepesh000 Sure. Please go ahead 👍

**Comment by ab-anand** [comment]
Also, in some cases, there is either `QUOTEE's` name missing or the `CONTRIBUTOR's`. In either case, just put it as `Unknown`

**Comment by mohitrakhade20** [comment]
I thought this is a public issue, That's why I did it @saideepesh000  you can design and format on top of my PR.
@ab-anand  I want to Thank you, this repo helped me to know open source contribution works.
